### ISSUE TITLE
LBT example

### ISSUE THREAD

**Issue by danshtr** [kd8bxp/Word100#1]
Thanks for sharing the library! 

Shouldn't:

 Word100lbt Word100(10); //use Word100lbt for the Little Buddy talker

be:

Word100 Word100lbt(10); //use Word100lbt for the Little Buddy talker

**Comment by kd8bxp** [comment]
It would make more sense - but I think the reason I did it like this was because the original 100+ word shield had different words in a different chip (there is a "normal" chip same words as the LBT, and a "ham" chip that has words related to the ham radio hobby).  When I ported this over to LBT I just keep consistent to what I had already done. (and I wasn't thinking about it honestly) - I may try to fix it thou.

**Comment by kd8bxp** [comment]
@danshtr I think I am going to leave this the way it is for now. I do think you are right and it would make more sense.  
The LBT works a little different then the 100+ Word and for now having it as it's own class just works. 
This was a learning experience for me, and hopefully I can learn how to do what you suggest soon.
